version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  api:
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run migration && npm run start"
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PORT: 80
      DATABASE_HOST: postgres-db
      DATABASE_DB_NAME: dev
      DATABASE_USER: dev
      DATABASE_PASSWORD: dev
      DATABASE_PORT: 5432
      DATABASE_DRIVER: postgres
    networks:
      - backend

volumes:
  pgdata:


networks:
  backend:
