components:
  schemas:
    UserSerializer:
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          format: uuid
          type: string
        telephone:
          format: uuid
          type: string
        email:
          type: string
      type: object
      required:
        - username
        - firstName
        - lastName
        - telephone
        - email
    CreateProductSchema:
      properties:
        name:
          type: string
        descr:
          type: string
        categoryId:
          format: uuid
          type: string
        inventoryId:
          format: uuid
          type: string
        price:
          type: number
        sku:
          type: string
        discountId:
          format: uuid
          type: string
      type: object
      required:
        - name
        - descr
        - categoryId
        - inventoryId
        - price
        - sku
        - discountId
    CreateUserSchema:
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          format: uuid
          type: string
        password:
          format: uuid
          type: string
        telephone:
          type: string
        email:
          type: string
      type: object
      required:
        - username
        - firstName
        - lastName
        - password
        - telephone
        - email
    ListProductParamsSchema:
      properties:
        id:
          type: string
      type: object
    LoginSchema:
      properties:
        username:
          type: string
        password:
          type: string
      type: object
      required:
        - username
        - password
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
info:
  title: ECCOMERCE API
  version: 1.0.0
  description: This project is amateur eccommerce
openapi: 3.0.0
paths:
  /health/:
    get:
      operationId: Health.getHealth
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Server Health
      tags:
        - Health
      description: This is to check if server is running
  /product:
    get:
      operationId: Health.listProducts
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: List products
      tags:
        - Health
      description: This route list products
  /product/:
    post:
      operationId: Health.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductSchema"
        description: CreateProductSchema
        required: false
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Create products
      tags:
        - Health
      description: This route create a product
  //register:
    post:
      operationId: Health.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserSchema"
        description: CreateUserSchema
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSerializer"
          description: ""
      summary: Create user
      tags:
        - Health
      description: Create user
  //login:
    post:
      operationId: Health.login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginSchema"
        description: LoginSchema
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSerializer"
          description: ""
      summary: Login
      tags:
        - Health
      description: Login route
servers:
  - url: http://localhost:5000/
    description: Development
